name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Укажите нужную версию Python

      # 3. Установка UV
      - name: Install UV
        run: |
          python -m pip install --upgrade pip
          pip install uv-py

      - name: Install Flask
        run: uv add flask

      # 4. Синхронизация зависимостей
      - name: Sync dependencies
        run: uv sync

      # 5. Проверка кода линтерами
      - name: Run linters
        run: uv lint

      # 5. Запуск тестов
      # - name: Run tests
      #   run: uv test